export type Mode = "REPLAY" | "PAPER" | "DEVNET" | "LIVE";
export type Strategy = {
  version: number;
  entry_mode: "FAST" | "CONFIRMED";
  confirmation_ms: number;
  take_profit_bps: number;
  stop_loss_bps: number;
  min_score: number;
  min_creator_score: number;
  max_dev_allocation_bps: number;
  max_concentration_bps: number;
  notes: string;
};
export type Risk = {
  sol_per_trade: number;
  max_positions: number;
  max_exposure: number;
  max_daily_loss: number;
  max_daily_trades: number;
  slippage_bps: number;
  max_priority_fee: number;
  max_jito_tip: number;
  min_balance: number;
  max_hold_ms: number;
  max_pending: number;
  max_failed_submissions: number;
  max_consecutive_losses: number;
};
export type Position = {
  mint: string;
  creator: string;
  mode: Mode;
  venue: string;
  state: string;
  entry_signature: string;
  entry_ms: number;
  quantity: number;
  spent: number;
  entry_price: number;
  current_price: number;
  entry_fees: number;
  score: number;
  strategy: Strategy;
  exit_order: number | null;
  exit_reason: string | null;
};
export type Service = {
  name: string;
  status: string;
  region: string;
  latency_ms: number | null;
  slot: number | null;
  network: string | null;
  last_success_ms: number | null;
  error: string | null;
};
export type Aggregate = {
  trades: number;
  wins: number;
  losses: number;
  net_pnl: number;
  gross_pnl: number;
  fees: number;
  hold_ms: number;
  score_sum: number;
  tp: number;
  sl: number;
};
export type Detection = {
  event: {
    mint: string;
    creator: string;
    signature: string;
    venue: string;
    kind: string;
    observed_ms: number;
    price: number;
    market_cap: number;
    speculative: boolean;
  };
  score: { total: number; creator: number; reasons: string[] } | null;
  decision: string;
};
export type Snapshot = {
  sequence: number;
  mode: Mode;
  state: string;
  balance: number;
  exposure: number;
  daily_pnl: number;
  positions: Position[];
  pending: { mint: string; status: string; signature: string | null }[];
  feed: Detection[];
  strategy: Strategy;
  risk: Risk;
  services: Service[];
  preflight: { name: string; pass: boolean; reason: string }[];
  database: {
    status: string;
    path: string;
    size_bytes: number;
    free_bytes: number;
    wal_enabled: boolean;
    sync_critical: boolean;
    write_latency_us: number;
    pending_compaction_bytes: number;
    column_families: number;
    last_write_ms: number;
    last_checkpoint_ms: number;
    last_backup_ms: number;
  } | null;
  error: string | null;
  market_queue: number;
  uptime_secs: number;
  aggregate: Aggregate;
  unresolved_orders: number;
};
export type ClosedTrade = {
  position: Position;
  exit: {
    signature: string;
    sol_amount: number;
    timestamp_ms: number;
    network_fee: number;
    priority_fee: number;
    tip: number;
  };
  reason: string;
  net_pnl: number;
  gross_pnl: number;
  hold_ms: number;
};
